MONGODB_DBNAME=$1
COLLECTION_NAME=$2
EXPORT_PATH=$3
TYPE=$4
FIELDS1=$5
FIELDS2=$6
FIELDS3=$7

sudo mongoexport -d $MONGODB_DBNAME -c $COLLECTION_NAME -o EXPORT_PATH --type $TYPE -f "$FIELDS1,$FIELDS2,$FIELDS3"
